### ISSUE TITLE
File manager's theme does not change

### ISSUE THREAD

**Issue by DoubleRHR** [LinxGem33/OSX-Arc-Shadow#4] opened 2017-04-23 16:11 UTC
Hi there. I've tried both 1.4.1 and 1.3.7 versions of shadow, and really any version of the OSX themes, and the file manager's theme does not change. I see other changes, such as in the font and taskbar, but it still seems the same. I'm using Ubuntu 16.04 and GTK3.18.9. I'm also willing to believe this is user error on my part. Here is a screenshot with the theme applied. Thank you!
![screenshot from 2017-04-23 09-09-44](https://cloud.githubusercontent.com/assets/20192625/25315113/c72c3e36-2804-11e7-817a-e38446e1ddfa.png)

**Comment by LinxGem33** [comment] 2017-04-23 17:04
@DoubleRHR 

hi before i go any further can you make sure that you have the correct system requirements installed as the theme wont function properly without them;

1. remove the theme collection before installing the below packages

2. `sudo apt-get install gnome-themes-standard`

3. `sudo apt-get install gtk2-engines-murrine`

after you reboot your system then install themes again and report back if the issue is not resolved.

kind rgards

**Comment by DoubleRHR** [comment] 2017-04-23 18:06
Alright, I've done as you've said. Those packages were already installed. Unfortunately, the issue still persists, no clue why. Thank you for your help so far.

**Comment by LinxGem33** [comment] 2017-04-23 19:08
@DoubleRHR 

appreciate the feed back, ill take a look into the issue and see if i can replicate it.

kind regards

**Comment by LinxGem33** [comment] 2017-05-01 02:49
@DoubleRHR 

hi is this issue still present on your system as i was unable to replicate the issue.

kind regards

**Comment by DoubleRHR** [comment] 2017-05-01 03:06
It still is. Thank you for your work so far.

**Comment by LinxGem33** [comment] 2017-05-14 23:06
going to close this issue as its not affecting multiple users if it does ill reopen.

**Closed by LinxGem33** 2017-05-14 23:06 UTC
Labels: awaiting response
